[workspace]
resolver = "2"
members = [
    "truffle-cli", "truffle-sim",
]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
thiserror = "2.0.12"
