[package]
name = "truffle-sqlx"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
truffle-sim = { path = "../truffle-sim" }
quote = "1.0.40"
syn = { version = "2.0.104", features = ["extra-traits"] }
