name: Benchmark
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        
      - name: Check Flake
        uses: DeterminateSystems/flake-checker-action@main
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."
          cache-on-failure: true
     
      - name: Benchmark in Nix Environment
        run: nix develop --command bash -c 'cargo bench'

